In [1]:
%load_ext autoreload
%autoreload 2


In [230]:
from glob import glob

import numpy as np
import problexity as px
from box import Box
import pandas as pd
from loguru import logger as log
from mlutils.datasets.dataset import Dataset
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.dummy import DummyClassifier
from sklearn.base import clone
from toolz.curried import filter
from sklearn.metrics import  accuracy_score


In [3]:
all_processed_data_files = glob(f"../datasets/notebooks/processed/*.csv")

all_file_names = [
    file.split('/')[-1].split('train')[0].rstrip('-') for file in all_processed_data_files if 'tra.csv' in file
]
print(all_file_names[:5])

['shuttle-5-5tra.csv', 'pima-5-5tra.csv', 'wisconsin-5-4tra.csv', 'automobile-5-2tra.csv', 'spambase-5-1tra.csv']


In [4]:
train_file_paths = [it for it in all_processed_data_files if 'tra.csv' in it]
dataset_names = {path.split('/')[-1].split('-')[0] for path in train_file_paths}
selected_datasets = []
for name in dataset_names:
    selected_datasets.append([p for p in train_file_paths if name in p][0])

In [5]:
param = Box(
    train_path = train_file_paths[5],
    ensemble_size=20
)

In [6]:

train_path = param.train_path.replace('tra', 'tst')
name = param.train_path.split("/")[-1].split('-')[0]
dataset = Dataset.read_dataset(param.train_path, train_path, name) \
    .encode_x_to_labels() \
    .encode_y_to_numeric_labels()

# bagging
bagging = BaggingClassifier(
    estimator=Perceptron(random_state=42),
    n_estimators=int(param.ensemble_size),
    max_samples=0.3,
    random_state=42)
bagging.fit(dataset.train.x, dataset.train.y)


BaggingClassifier(estimator=Perceptron(random_state=42), max_samples=0.3,
                  n_estimators=20, random_state=42)

In [7]:
import warnings
warnings.filterwarnings("ignore")


In [8]:
test_x = [
    [0, 0], [10,10], [0, 10], [10, 0], [5, 5], [5, 7]
]
test_y = [1, 1, 1, 1, 0, 0]
px.f2(test_x, test_y)

0.0

In [215]:
labels = np.array([1,3,2,2,2,2,1,2,3,4,5,5,5,5,6])

In [217]:
labels_c = labels.copy()

In [218]:
labels_c[labels_c != 2] = 0

In [220]:
labels_c

array([0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0])

In [213]:
np.putmask(labels, labels!=2, 1)

In [214]:
labels

array([1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1])

In [203]:
np.array([1,2,2,2,2,1]) != 2

array([ True, False, False, False, False,  True])

In [228]:
def find_best_cutoff_for(dataset, dimension, cutoff_function=px.f2):
    log.debug("Cutoff calculation dataset size {}", len(dataset.x))
    possible_cutoffs = sorted(set(dataset.x[:, dimension]))
    log.debug("Possible cutoffs size {}", len(possible_cutoffs))
    samples_in_cutoffs = [
        Box({
            'cutoff': cutoff,
            'left': {
                'x': dataset.x[dataset.x[:, dimension] <= cutoff],
                'y': dataset.y[dataset.x[:, dimension] <= cutoff],
            },
            'right': {
                'x': dataset.x[dataset.x[:, dimension] > cutoff],
                'y': dataset.y[dataset.x[:, dimension] > cutoff],
            }
         })
        for cutoff in possible_cutoffs
    ]

    def should_pass(cutoff_samples):
        left_size = len(cutoff_samples.left.x)
        right_size = len(cutoff_samples.right.x)
        return left_size > 5 and right_size > 5 and left_size/len(dataset.x) > 0.1 and right_size/len(dataset.x) > 0.1

    samples_in_cutoffs_filtered = [
        cutoff_samples for cutoff_samples in samples_in_cutoffs if should_pass(cutoff_samples)
    ]

    for it in samples_in_cutoffs_filtered:
        try:

            left_complexities = []
            for label in np.unique(it.left.y):
                ovo_y = it.left.y.copy()
                ovo_y[ovo_y != label] = 0
                ovo_y[ovo_y == label] = 1
                if len(np.unique(ovo_y)) == 1:
                    continue

                log.debug(ovo_y)
                left_complexity = cutoff_function(it.left.x, ovo_y)
                left_complexities.append(left_complexity)


            right_complexities = []
            for label in np.unique(it.right.y):
                ovo_y = it.left.y.copy()
                ovo_y[ovo_y != label] = 0
                ovo_y[ovo_y == label] = 1
                if len(np.unique(ovo_y)) == 1:
                    continue
                log.debug(ovo_y)
                right_complexity = cutoff_function(it.left.x, ovo_y)
                right_complexities.append(right_complexity)
                
        except Exception as e:
            raise e
            log.exception(e)
            return None

        it.left_complexity = np.mean(left_complexities)
        it.right_complexity = np.mean(right_complexities)

    lowest_complexity = min(samples_in_cutoffs_filtered, key = lambda it: it.left_complexity + it.right_complexity)

    if lowest_complexity is None:
        return None


    return lowest_complexity.cutoff, lowest_complexity.left_complexity + lowest_complexity.right_complexity


In [195]:
def recursive_cutoff(dataset, current_conditions=None, recursion_level=0, min_samples = 10, recursion_limit = 4, cutoff_function = px.f2):
    log.debug("Recursion {}", recursion_level)

    if current_conditions is None:
        current_conditions = list()

    log.debug("Current conditions = {}", current_conditions)

    if recursion_limit != -1 and recursion_level >= recursion_limit:
        log.debug("Recursion limit reached")
        log.debug(current_conditions)
        return {" and ".join(current_conditions)}
    recursion_level = recursion_level + 1
    log.debug("Recursion level = {}", recursion_level)

    if len(dataset.x) < min_samples:
        log.debug("Min samples reached")
        log.debug(current_conditions)
        return {" and ".join(current_conditions)}

    features_count = dataset.x.shape[1]

    best_cutoff_by_dimension = {}

    for feature_idx in range(features_count):
        cutoff_and_value = find_best_cutoff_for(Box(x=dataset.x, y=dataset.y), feature_idx, cutoff_function=cutoff_function)
        if cutoff_and_value is None:
            continue

        cutoff, value = cutoff_and_value

        best_cutoff_by_dimension[feature_idx] = {
            'cutoff': cutoff,
            'value': value
        }

    log.debug("Values={}", best_cutoff_by_dimension)

    if not best_cutoff_by_dimension:
        log.debug("Returning")
        log.debug(current_conditions)
        return {" and ".join(current_conditions)}

    best_cutoff_entry = min(best_cutoff_by_dimension.items(), key=lambda it: it[1]['cutoff'])
    best_cutoff_dimension = best_cutoff_entry[0]
    best_cutoff = best_cutoff_entry[1]['cutoff']
    best_cutoff_value = best_cutoff_entry[1]['value']

    log.debug("Best cutoff value = {} ({} at dim {})", best_cutoff_value, best_cutoff, best_cutoff_dimension)

    left_conditions = f"col{best_cutoff_dimension} <= {best_cutoff}"
    right_conditions = f"col{best_cutoff_dimension} > {best_cutoff}"
    log.debug(left_conditions)
    log.debug(right_conditions)

    left_indicies = dataset.x[:, best_cutoff_dimension] <= best_cutoff
    right_indicies = dataset.x[:, best_cutoff_dimension] > best_cutoff

    left_statements = recursive_cutoff(Box(x=dataset.x[left_indicies], y=dataset.y[left_indicies]), current_conditions + [left_conditions], recursion_level + 1)
    right_statements = recursive_cutoff(Box(x=dataset.x[right_indicies], y=dataset.y[right_indicies]), current_conditions + [right_conditions], recursion_level + 1)
    log.debug("Left statements {}", left_statements)
    log.debug("Right statments {}", right_statements)

    return left_statements.union(right_statements)


In [196]:
def as_classifier(clf_by_rule):
    def predict(X):
        df = pd.DataFrame(X, columns=[f"col{i}" for i in range(X.shape[1])])

        for rule, clf in clf_by_rule.items():
            idx_to_predict = df.query(rule).index
            to_predict = df.loc[idx_to_predict] \
                .drop('prediction', axis=1, errors='ignore') \
                .drop('rule', axis=1, errors='ignore') \
                .to_numpy()

            if len(to_predict) == 0:
                continue

            df.loc[idx_to_predict, 'prediction'] = clf.predict(df.loc[df.query(rule).index] \
                                                               .drop('prediction', axis=1, errors='ignore') \
                                                               .drop('rule', axis=1, errors='ignore') \
                                                               .to_numpy())
            df.loc[df.query(rule).index, 'rule'] = rule

        return df.prediction.to_numpy()

    return Box({
        "predict": predict
    })

In [235]:
def train_quad_clf(train_x, train_y, base_clf = Perceptron(random_state=42), min_samples = 10, recursion_limit = -1):
    statements = recursive_cutoff(Box(
        x=train_x,
        y=train_y
    ), min_samples=min_samples, recursion_limit=recursion_limit)
    
    clf_by_rules = {}
    x_for_indices_calculation = pd.DataFrame(dataset.train.x)
    for col in range(x_for_indices_calculation.shape[1]):
        x_for_indices_calculation[f"col{col}"] = x_for_indices_calculation[col]
    indices_by_each_statement = {
        query: x_for_indices_calculation.query(query).index for query in statements
    }
    
    for query, idx in indices_by_each_statement.items():
        x_train = dataset.train.x[idx]
        y_train = dataset.train.y[idx]
    
        if len(np.unique(y_train)) == 1:
            clf_by_rules[query] = DummyClassifier(strategy="constant", constant=y_train[0]).fit(x_train, y_train)
        else:
            clf = clone(base_clf)
            clf.fit(x_train, y_train)
            clf_by_rules[query] = clf
    
    return as_classifier(clf_by_rules)

In [232]:
train_quad_clf(dataset.train.x, dataset.train.y).predict

2023-08-12 17:47:41.318 | DEBUG    | __main__:recursive_cutoff:2 - Recursion 0
2023-08-12 17:47:41.319 | DEBUG    | __main__:recursive_cutoff:7 - Current conditions = []
2023-08-12 17:47:41.319 | DEBUG    | __main__:recursive_cutoff:14 - Recursion level = 1
2023-08-12 17:47:41.319 | DEBUG    | __main__:find_best_cutoff_for:2 - Cutoff calculation dataset size 142
2023-08-12 17:47:41.320 | DEBUG    | __main__:find_best_cutoff_for:4 - Possible cutoffs size 107
2023-08-12 17:47:41.327 | DEBUG    | __main__:find_best_cutoff_for:40 - [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
2023-08-12 17:47:41.327 | DEBUG    | __main__:find_best_cutoff_for:40 - [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
2023-08-12 17:47:41.328 | DEBUG    | __main__:find_best_cutoff_for:52 - [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
2023-08-12 17:47:41.328 | DEBUG    | __main__:find_best_cutoff_for:52 - [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
2023-08-12 17:47:41.329 | DEBUG    | __mai

<function __main__.as_classifier.<locals>.predict(X)>

In [159]:
dataset.train.x

array([[ 54,  62,  56, ...,  43,  73,  87],
       [102,  50,  42, ...,  25,  91, 100],
       [104,  45,  39, ...,  42,  98,  95],
       ...,
       [ 38,  89,  31, ...,  19,   1,  40],
       [ 61,  83,  33, ...,   1,  13,  46],
       [ 65,  99,  41, ...,  13,   9,  56]])

In [236]:
accuracy_score(
    train_quad_clf(dataset.train.x, dataset.train.y).predict(dataset.test.x),
    dataset.test.y
)

2023-08-12 17:48:58.124 | DEBUG    | __main__:recursive_cutoff:2 - Recursion 0
2023-08-12 17:48:58.125 | DEBUG    | __main__:recursive_cutoff:7 - Current conditions = []
2023-08-12 17:48:58.125 | DEBUG    | __main__:recursive_cutoff:14 - Recursion level = 1
2023-08-12 17:48:58.125 | DEBUG    | __main__:find_best_cutoff_for:2 - Cutoff calculation dataset size 142
2023-08-12 17:48:58.126 | DEBUG    | __main__:find_best_cutoff_for:4 - Possible cutoffs size 107
2023-08-12 17:48:58.132 | DEBUG    | __main__:find_best_cutoff_for:40 - [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
2023-08-12 17:48:58.133 | DEBUG    | __main__:find_best_cutoff_for:40 - [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
2023-08-12 17:48:58.133 | DEBUG    | __main__:find_best_cutoff_for:52 - [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1]
2023-08-12 17:48:58.134 | DEBUG    | __main__:find_best_cutoff_for:52 - [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
2023-08-12 17:48:58.134 | DEBUG    | __mai

0.9722222222222222

In [240]:
accuracy_score(
    DecisionTreeClassifier(random_state=42).fit(dataset.train.x, dataset.train.y).predict(dataset.test.x),
    dataset.test.y
)

0.9444444444444444

In [237]:
accuracy_score(
    Perceptron(random_state=42).fit(dataset.train.x, dataset.train.y).predict(dataset.test.x),
    dataset.test.y
)

0.9444444444444444

In [ ]:
original_ds = dataset

In [ ]:

for statement in statements:
    

In [76]:
ds.query("col3 > 31 and col3 > 39").index

Index([ 16,  51,  52,  53,  57,  59,  60,  61,  62,  66,  72,  74,  78,  80,
        81,  84,  85,  86,  87,  88,  89,  90,  91,  94,  97,  98,  99, 100,
       102, 105, 106, 107, 108, 109, 112, 113, 114, 116, 118, 119, 120, 121,
       126, 133, 136, 137, 138, 139, 140, 141],
      dtype='int64')

In [77]:
ds.query("col3 > 31 and col3 > 39")

0    1   2   3   4   5    6   7   8    9  ...  col3  col4  col5  col6   
16    50   54  69  52  41  57   76  26  57   29  ...    52    41    57    76  \
51    88   22  56  52   6  70   82   5  55   27  ...    52     6    70    82   
52    49   33  51  57  46  80   84   5  59   26  ...    57    46    80    84   
53    14    6  27  42  20  81   55   0  43   23  ...    42    20    81    55   
57    38   96  35  47  20  65   71  24  58   10  ...    47    20    65    71   
59     6   55  40  44   4  32   42  27  26   15  ...    44     4    32    42   
60    18   13  27  49   0  40   39  23  29    0  ...    49     0    40    39   
61    15   22  37  45   6   9   29  28  42   30  ...    45     6     9    29   
62    37   24  23  40   2   5   37  32  41   20  ...    40     2     5    37   
66    10   57  62  43  44  16   24   1  40    9  ...    43    44    16    24   
72    25   66  40  42  18  53   53  17  25   15  ...    42    18    53    53   
74    27   68  24  45  10  21   46  36  32   13  ...    45    10    21    46   
78    32   65  17  42   8  52   61   9  22    2  ...    42     8    52    61   
80     0    0  42  42   8  49   50  23  33   21  ...    42     8    49    50   
81    18   17  42  46   4  53   62  24  16   16  ...    46     4    53    62   
84     3   54  70  56  36  77  116  26  55   73  ...    56    36    77   116   
85    27  107  61  54  21  40   54  24  48    4  ...    54    21    40    54   
86    50  114  14  43   6  56   75  13  63   11  ...    43     6    56    75   
87    13  106  34  42   3  67   93   5  79   15  ...    42     3    67    93   
88    17   60  17  42   5  54   75  19  26   14  ...    42     5    54    75   
89    28   24  26  43   6  62   97  20  51   36  ...    43     6    62    97   
90    26   29  27  51   8  41   66  21  56    5  ...    51     8    41    66   
91    16  105  33  45   2  37   43  23  26   11  ...    45     2    37    43   
94    41   61  35  50  18   1   26  10   8   69  ...    50    18     1    26   
97    22  110  46  42   9   5    0  29   6   34  ...    42     9     5     0   
98    33  113  54  52  16  26    9  35  18   53  ...    52    16    26     9   
99    42   77  52  50  20  43    9  29   7   52  ...    50    20    43     9   
100   47   74  59  42  16  13    2  29   5   47  ...    42    16    13     2   
102   71   82  60  48  17  14    4  28   1   42  ...    48    17    14     4   
105   54   90  15  42  21  11    5  24  24   37  ...    42    21    11     5   
106   45  109  41  43   6  22   11  26  10   88  ...    43     6    22    11   
107   52   98  31  43  31   8   35  17  20  100  ...    43    31     8    35   
108   69   81  53  50  40   7   38   6  23   94  ...    50    40     7    38   
109   53   48  63  53  33  40   30   9  40   83  ...    53    33    40    30   
112   55  112  29  45  13  24   10  34  39   90  ...    45    13    24    10   
113   29   79  54  55  17  30    8  35  20   86  ...    55    17    30     8   
114  101   34  59  52  18  64   32  29  76  106  ...    52    18    64    32   
116   43   85  49  45  25  20    9  33  13   66  ...    45    25    20     9   
118   85   73  27  45  10   4   13  22  15  101  ...    45    10     4    13   
119   67   92  51  47  29  22   22  24  35  105  ...    47    29    22    22   
120   73   70  58  51  24  14   21  20  38   95  ...    51    24    14    21   
121   65  108  67  52  30  33   23  10  19   93  ...    52    30    33    23   
126   96  103  62  51  16  36   17  31  26   98  ...    51    16    36    17   
133   50   95  29  46   5  20   39  34  41   50  ...    46     5    20    39   
136   39   39  25  46   4   5   44  27  42   25  ...    46     4     5    44   
137   11   20   9  41   6  33   40  13  37    1  ...    41     6    33    40   
138    9   58  64  56  12  39   58  32  50   19  ...    56    12    39    58   
139   38   89  31  43  25  22   27   2   9   53  ...    43    25    22    27   
140   61   83  33  43  12  31   17  25  23   92  ...    43    12    31    17   
141   6

In [78]:
dataset.train.y[ds.query("col3 > 31 and col3 > 39").index]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 1, 1, 2, 2, 2])

In [58]:
sections

{'col3 <= 31 and col7 <= 14 and col3 <= 6',
 'col3 <= 31 and col7 <= 14 and col3 > 6',
 'col3 <= 31 and col7 > 14 and col4 <= 14',
 'col3 <= 31 and col7 > 14 and col4 > 14',
 'col3 > 31 and col3 <= 39 and col7 <= 9',
 'col3 > 31 and col3 <= 39 and col7 > 9',
 'col3 > 31 and col3 > 39'}

In [23]:
ds = pd.DataFrame(dataset.train.x)

In [26]:
for col in range(ds.shape[1]):
    ds[f"col{col}"] = ds[col]

In [69]:
ds.query("col3 > 31 and col3 > 39").index

Index([ 16,  51,  52,  53,  57,  59,  60,  61,  62,  66,  72,  74,  78,  80,
        81,  84,  85,  86,  87,  88,  89,  90,  91,  94,  97,  98,  99, 100,
       102, 105, 106, 107, 108, 109, 112, 113, 114, 116, 118, 119, 120, 121,
       126, 133, 136, 137, 138, 139, 140, 141],
      dtype='int64')

In [61]:
len(ds)

142

In [60]:
{
    query: len(ds.query(query)) for query in sections
}

{'col3 > 31 and col3 <= 39 and col7 <= 9': 6,
 'col3 > 31 and col3 > 39': 50,
 'col3 > 31 and col3 <= 39 and col7 > 9': 24,
 'col3 <= 31 and col7 <= 14 and col3 > 6': 32,
 'col3 <= 31 and col7 > 14 and col4 <= 14': 7,
 'col3 <= 31 and col7 > 14 and col4 > 14': 17,
 'col3 <= 31 and col7 <= 14 and col3 <= 6': 6}

In [17]:
pd.DataFrame(dataset.train.x).iloc[0]

0      54
1      62
2      56
3      29
4      20
5      64
6     102
7      13
8      78
9      68
10     43
11     73
12     87
Name: 0, dtype: int64

In [14]:
import pandas as pd
pd.DataFrame(dataset.train.x).query('str(0) < 34', engine="python")

ValueError: "str" is not a supported function

In [79]:
np.array([None, 1, 4, 5, 2, None ]) == None

array([ True, False, False, False, False,  True])

In [ ]:
recursive_cutoff

In [126]:
dataset.train

Box({'x': array([[ 20, 113,  25, ...,  43,  75,  33],
       [ 18, 113,  15, ...,  36,  13,   6],
       [  2, 113,   9, ...,  47,  31,   9],
       ...,
       [ 14, 116,  10, ...,  35,  13,   6],
       [  6, 113,   9, ...,  42,  17,   5],
       [  2, 113,  39, ...,  75,  55,   7]]), 'y': array([3, 0, 0, ..., 0, 0, 0])})

In [146]:
best_cutoff, values = find_best_cutoff_for(dataset.train, 1)

In [ ]:
best_cutoff

In [128]:
values

161

In [ ]:
values

In [107]:
for cutoff in possible_cutoffs:
    left_samples_idx = dataset.train.x[:, dimension_considered] <= cutoff
    right_samples_idx = dataset.train.x[:, dimension_considered] > cutoff
    left_samples_x = dataset.train.x[left_samples_idx]
    left_samples_y = dataset.train.y[left_samples_idx]

    right_samples_x = dataset.train.x[right_samples_idx]
    right_samples_y = dataset.train.y[right_samples_idx]

    if len(left_samples_idx) < 2 or len(right_samples_idx) < 2:
            print("nope")

    if len(set(left_samples_y)) == 1 or len(set(right_samples_y)) == 1:
        print("nope")
    else:

        left_complexity = px.l1(left_samples_x, left_samples_y)
        right_complexity = px.l1(right_samples_x, right_samples_y)
        print(f"l:{left_complexity} r:{right_complexity}")

        complexities.append((left_complexity, right_complexity))




nope
nope


/Users/bgulowaty/studia/projekty/quad-splits/.venv/lib/python3.8/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
/Users/bgulowaty/studia/projekty/quad-splits/.venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


ValueError: shapes (27,) and (9,39) not aligned: 27 (dim 0) != 9 (dim 0)

In [76]:
complexities_summed_for_both = [l+r for (l, r) in complexities]


In [80]:
lowest_complexity_idx = np.argmin(complexities_summed_for_both)

In [81]:
lowest_complexity_idx

17

In [82]:
complexities[17]

(0.0042562119713455025, 0.0006903428702922451)

In [83]:
current_split_conditions = []